Set XACT_ABORT ON
BEGIN TRAN

MERGE [dbo].[testa] AS TARGET
USING (VALUES
(1,1, 'a'),
(3,1, 'a'),
(4,1, 'a'),
(6,1, 'a')
) AS SOURCE(a,b,c)
ON TARGET.a=SOURCE.a AND TARGET.c=SOURCE.c
WHEN NOT MATCHED
THEN INSERT([a],[b],[c])
VALUES(SOURCE.a,SOURCE.b,SOURCE.c);
COMMIT TRAN

Set XACT_ABORT OFF
GO
